spring:
  application:
    name: "Accounts"

  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/Accounts"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


  config:
    activate:
      on-profile: